### ISSUE TITLE
Urls regex

### ISSUE THREAD

**Issue by ipatovanton** [Timrael/social_shares#13]
Links like this doesn't works
https://slon.ru/posts/61533?utm_source=slon.ru&utm_medium=rss&utm_campaign=all

And this works
https://slon.ru/posts/61533

**Comment by Timrael** [comment]
@ipatovanton could you please give more details: like what social network doesn't work and version of the gem?

**Comment by ipatovanton** [comment]
facebook and social_shares (0.2.7)

**Comment by Timrael** [comment]
```ruby
2.2.2 :002 > require 'social_shares'
 => true
2.2.2 :003 > SocialShares.facebook 'https://slon.ru/posts/61533?utm_source=slon.ru&utm_medium=rss&utm_campaign=all'
 => 47
2.2.2 :004 > SocialShares.facebook 'https://slon.ru/posts/61533'
 => 47
```

Is this behavior ok?

**Comment by Timrael** [comment]
facebook don't give a sh*t about your get params =)

**Comment by ipatovanton** [comment]
Thanks all works
