### ISSUE TITLE
Facebook FQL has been deprecated

### ISSUE THREAD

**Issue by nirdil** [Timrael/social_shares#17]
The current used method for getting facebook shares will not work as the FQL API was recently deprecated. You'll get the following error message: "(#12) fql is deprecated for versions v2.1 and higher"
As a (poor) alternative I suggest looking at the following API:
https://graph.facebook.com/?id=http://google.com&fields=id,og_object{image,engagement,likes.summary(true),comments.summary(true).limit(100)},share

**Comment by Timrael** [comment]
Thanks, I will implement it soon.

**Comment by Timrael** [comment]
Done, but we need to get sure that share.share_count is not a sum of likes + shares + comments. Do you have a history of previous requests to check it?
