### ISSUE TITLE
Memory leaks with Threads

### ISSUE THREAD

**Issue by joenas** [Timrael/social_shares#21]
I created a [sinatra app](https://github.com/joenas/social_shares_app) using this gem. After a while I noticed it was eating memory on the server like crazy. I forked and [removed the threading](https://github.com/joenas/social_shares/tree/no_threads), which resolved the issue. 

I did try to solve it and keep threads but no luck. I think its related to something like [this](https://stackoverflow.com/a/41915534). I'll have another go at fixing it if I get the time.

**Comment by joenas** [comment]
Haven't had time to check yet but might be related to [this](https://bugs.ruby-lang.org/issues/13772)?

**Comment by Timrael** [comment]
I suppose it was fixed in ruby 2.4.2
