### ISSUE TITLE
Urls regex

### ISSUE THREAD

**Issue by ipatovanton** [Timrael/social_shares#8]
Urls like this doesn't work if you count vkontakte shares
http://top.rbc.ru/politics/15/02/2015/54e0793a9a7947c1231b4967#xtor=AL-[internal_traffic]--[rss.rbc.ru]-[top_stories]

This works
http://top.rbc.ru/politics/15/02/2015/54e0793a9a7947c1231b4967

**Comment by Timrael** [comment]
Thanks for reporting, fix it in version 0.2.3 :+1:
