### ISSUE TITLE
http vs https counts?

### ISSUE THREAD

**Issue by phallstrom** [Timrael/social_shares#9]
Just came across your gem. Neat. Noticed that facebook returns the same count regardless of URL scheme (http vs https).  Twitter, Reddit, and Pinterest (maybe others) have different counts.

Should those that change be tweaked to check both http and https and sum the count? If there's an interest in that I'd be willing to submit a PR.

**Comment by Timrael** [comment]
Hi, sorry for the long wait. I think we should leave it on lib users and let them decide sum the count or not. And make some remark about it.
